import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../global.css";

import Sidebar from "@/components/AdminSideBar/AdminSideBar";
import AdminClientOnly from "./AdminClientOnly";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Grantaly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div >
        <AdminClientOnly>
          {children}
        </AdminClientOnly>
    </div>
  );
}
