// app/layout.tsx (or app/layout.js if using JavaScript)

import './globals.css';
import ClientOnly from './components/ClientOnly/ClientOnly';
import getCurrentUser from './actions/getCurrentUser';

import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Grantaly',
  description: 'Generated by create next app',
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        <Toaster position="bottom-right" reverseOrder={false} />
        <ClientOnly user={user}>
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
