import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../global.css";

import Sidebar from "@/components/AdminSideBar/AdminSideBar";
import UserClientOnly from "./UserClientOnly";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Grantaly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div >
        <UserClientOnly>
          {children}
        </UserClientOnly>
    </div>
  );
}
